# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - head_controller
    - waist_controller
    - left_leg_controller
    - right_leg_controller
    - left_arm_controller
    - right_arm_controller
    - left_hand_controller
    - right_hand_controller
    - body_controller

  head_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - head1_y_joint
      - head2_p_joint
    action_ns: follow_joint_trajectory
    default: true
  waist_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - waist1_y_joint
      - waist2_p_joint
    action_ns: follow_joint_trajectory
    default: true
  left_leg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l_leg1_hip_y_joint
      - l_leg2_hip_r_joint
      - l_leg3_hip_p_joint
      - l_leg4_knee_p_joint
      - l_leg5_ankle_p_joint
      - l_leg6_ankle_r_joint
    action_ns: follow_joint_trajectory
    default: true
  right_leg_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r_leg1_hip_y_joint
      - r_leg2_hip_r_joint
      - r_leg3_hip_p_joint
      - r_leg4_knee_p_joint
      - r_leg5_ankle_p_joint
      - r_leg6_ankle_r_joint
    action_ns: follow_joint_trajectory
    default: true
  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l_arm1_shoulder_p_joint
      - l_arm2_shoulder_r_joint
      - l_arm3_shoulder_y_joint
      - l_arm4_elbow_p_joint
      - l_arm5_wrist_y_joint
      - l_arm6_wrist_p_joint
      - l_arm7_wrist_r_joint
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r_arm1_shoulder_p_joint
      - r_arm2_shoulder_r_joint
      - r_arm3_shoulder_y_joint
      - r_arm4_elbow_p_joint
      - r_arm5_wrist_y_joint
      - r_arm6_wrist_p_joint
      - r_arm7_wrist_r_joint
    action_ns: follow_joint_trajectory
    default: true
  left_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l_index_mcp_joint
      - l_middle_mcp_joint
      - l_pinky_mcp_joint
      - l_ring_mcp_joint
      - l_thumb_cmc_y_joint
      - l_thumb_cmc_p_joint
    action_ns: follow_joint_trajectory
    default: true
  right_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - r_index_mcp_joint
      - r_middle_mcp_joint
      - r_pinky_mcp_joint
      - r_ring_mcp_joint
      - r_thumb_cmc_y_joint
      - r_thumb_cmc_p_joint
    action_ns: follow_joint_trajectory
    default: true
  body_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - l_leg1_hip_y_joint
      - l_leg2_hip_r_joint
      - l_leg3_hip_p_joint
      - l_leg4_knee_p_joint
      - l_leg5_ankle_p_joint
      - l_leg6_ankle_r_joint
      - r_leg1_hip_y_joint
      - r_leg2_hip_r_joint
      - r_leg3_hip_p_joint
      - r_leg4_knee_p_joint
      - r_leg5_ankle_p_joint
      - r_leg6_ankle_r_joint
      - waist1_y_joint
      - waist2_p_joint
      - head1_y_joint
      - head2_p_joint
      - l_arm1_shoulder_p_joint
      - l_arm2_shoulder_r_joint
      - l_arm3_shoulder_y_joint
      - l_arm4_elbow_p_joint
      - l_arm5_wrist_y_joint
      - l_arm6_wrist_p_joint
      - l_arm7_wrist_r_joint
      - l_index_mcp_joint
      - l_middle_mcp_joint
      - l_pinky_mcp_joint
      - l_ring_mcp_joint
      - l_thumb_cmc_y_joint
      - l_thumb_cmc_p_joint
      - r_arm1_shoulder_p_joint
      - r_arm2_shoulder_r_joint
      - r_arm3_shoulder_y_joint
      - r_arm4_elbow_p_joint
      - r_arm5_wrist_y_joint
      - r_arm6_wrist_p_joint
      - r_arm7_wrist_r_joint
      - r_index_mcp_joint
      - r_middle_mcp_joint
      - r_pinky_mcp_joint
      - r_ring_mcp_joint
      - r_thumb_cmc_y_joint
      - r_thumb_cmc_p_joint
    action_ns: follow_joint_trajectory
    default: true
