# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ankle_p_joint:
    has_velocity_limits: true
    max_velocity: 2.5099999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  head1_y_joint:
    has_velocity_limits: true
    max_velocity: 6.0
    has_acceleration_limits: false
    max_acceleration: 0
  head2_p_joint:
    has_velocity_limits: true
    max_velocity: 8.0
    has_acceleration_limits: false
    max_acceleration: 0
  knee_p_joint:
    has_velocity_limits: true
    max_velocity: 2.5099999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm1_shoulder_p_joint:
    has_velocity_limits: true
    max_velocity: 3.8999999999999999
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm2_shoulder_r_joint:
    has_velocity_limits: true
    max_velocity: 3.8999999999999999
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm3_shoulder_y_joint:
    has_velocity_limits: true
    max_velocity: 3.7999999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm4_elbow_p_joint:
    has_velocity_limits: true
    max_velocity: 3.7999999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm5_wrist_y_joint:
    has_velocity_limits: true
    max_velocity: 4.2999999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm6_wrist_p_joint:
    has_velocity_limits: true
    max_velocity: 7.7000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm7_wrist_r_joint:
    has_velocity_limits: true
    max_velocity: 7.7000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  l_index_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_middle_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_pinky_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_ring_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_thumb_cmc_p_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  l_thumb_cmc_y_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm1_shoulder_p_joint:
    has_velocity_limits: true
    max_velocity: 3.8999999999999999
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm2_shoulder_r_joint:
    has_velocity_limits: true
    max_velocity: 3.8999999999999999
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm3_shoulder_y_joint:
    has_velocity_limits: true
    max_velocity: 3.7999999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm4_elbow_p_joint:
    has_velocity_limits: true
    max_velocity: 3.7999999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm5_wrist_y_joint:
    has_velocity_limits: true
    max_velocity: 4.2999999999999998
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm6_wrist_p_joint:
    has_velocity_limits: true
    max_velocity: 7.7000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  r_arm7_wrist_r_joint:
    has_velocity_limits: true
    max_velocity: 7.7000000000000002
    has_acceleration_limits: false
    max_acceleration: 0
  r_index_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  r_middle_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  r_pinky_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  r_ring_mcp_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  r_thumb_cmc_p_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  r_thumb_cmc_y_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 0
  waist1_p_joint:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  waist2_y_joint:
    has_velocity_limits: true
    max_velocity: 3.1400000000000001
    has_acceleration_limits: false
    max_acceleration: 0