# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - trunk_controller
    - head_controller
    - left_arm_controller
    - right_arm_controller
    - body_controller
    - left_hand_controller
    - right_hand_controller

  trunk_controller:
    type: FollowJointTrajectory
    joints:
      - ankle_p_joint
      - knee_p_joint
      - waist1_p_joint
      - waist2_y_joint
    action_ns: follow_joint_trajectory
    default: true
  head_controller:
    type: FollowJointTrajectory
    joints:
      - head1_y_joint
      - head2_p_joint
    action_ns: follow_joint_trajectory
    default: true
  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - l_arm1_shoulder_p_joint
      - l_arm2_shoulder_r_joint
      - l_arm3_shoulder_y_joint
      - l_arm4_elbow_p_joint
      - l_arm5_wrist_y_joint
      - l_arm6_wrist_p_joint
      - l_arm7_wrist_r_joint
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - r_arm1_shoulder_p_joint
      - r_arm2_shoulder_r_joint
      - r_arm3_shoulder_y_joint
      - r_arm4_elbow_p_joint
      - r_arm5_wrist_y_joint
      - r_arm6_wrist_p_joint
      - r_arm7_wrist_r_joint
    action_ns: follow_joint_trajectory
    default: true
  body_controller:
    type: FollowJointTrajectory
    joints:
      - ankle_p_joint
      - knee_p_joint
      - waist1_p_joint
      - waist2_y_joint
      - head1_y_joint
      - head2_p_joint
      - l_arm1_shoulder_p_joint
      - l_arm2_shoulder_r_joint
      - l_arm3_shoulder_y_joint
      - l_arm4_elbow_p_joint
      - l_arm5_wrist_y_joint
      - l_arm6_wrist_p_joint
      - l_arm7_wrist_r_joint
      - r_arm1_shoulder_p_joint
      - r_arm2_shoulder_r_joint
      - r_arm3_shoulder_y_joint
      - r_arm4_elbow_p_joint
      - r_arm5_wrist_y_joint
      - r_arm6_wrist_p_joint
      - r_arm7_wrist_r_joint
    action_ns: follow_joint_trajectory
    default: true
  left_hand_controller:
    type: FollowJointTrajectory
    joints:
      - l_index_mcp_joint
      - l_middle_mcp_joint
      - l_pinky_mcp_joint
      - l_ring_mcp_joint
      - l_thumb_cmc_y_joint
      - l_thumb_cmc_p_joint
    action_ns: follow_joint_trajectory
    default: true
  right_hand_controller:
    type: FollowJointTrajectory
    joints:
      - r_index_mcp_joint
      - r_middle_mcp_joint
      - r_pinky_mcp_joint
      - r_ring_mcp_joint
      - r_thumb_cmc_y_joint
      - r_thumb_cmc_p_joint
    action_ns: follow_joint_trajectory
    default: true