# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    waist_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

head_controller:
  ros__parameters:
    joints:
      - head1_y_joint
      - head2_p_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
waist_controller:
  ros__parameters:
    joints:
      - waist1_y_joint
      - waist2_p_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_leg_controller:
  ros__parameters:
    joints:
      - l_leg1_hip_y_joint
      - l_leg2_hip_r_joint
      - l_leg3_hip_p_joint
      - l_leg4_knee_p_joint
      - l_leg5_ankle_p_joint
      - l_leg6_ankle_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_leg_controller:
  ros__parameters:
    joints:
      - r_leg1_hip_y_joint
      - r_leg2_hip_r_joint
      - r_leg3_hip_p_joint
      - r_leg4_knee_p_joint
      - r_leg5_ankle_p_joint
      - r_leg6_ankle_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_arm_controller:
  ros__parameters:
    joints:
      - l_arm1_shoulder_p_joint
      - l_arm2_shoulder_r_joint
      - l_arm3_shoulder_y_joint
      - l_arm4_elbow_p_joint
      - l_arm5_wrist_y_joint
      - l_arm6_wrist_p_joint
      - l_arm7_wrist_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - r_arm1_shoulder_p_joint
      - r_arm2_shoulder_r_joint
      - r_arm3_shoulder_y_joint
      - r_arm4_elbow_p_joint
      - r_arm5_wrist_y_joint
      - r_arm6_wrist_p_joint
      - r_arm7_wrist_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_hand_controller:
  ros__parameters:
    joints:
      - l_index_mcp_joint
      - l_middle_mcp_joint
      - l_pinky_mcp_joint
      - l_ring_mcp_joint
      - l_thumb_cmc_y_joint
      - l_thumb_cmc_p_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_hand_controller:
  ros__parameters:
    joints:
      - r_index_mcp_joint
      - r_middle_mcp_joint
      - r_pinky_mcp_joint
      - r_ring_mcp_joint
      - r_thumb_cmc_y_joint
      - r_thumb_cmc_p_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
body_controller:
  ros__parameters:
    joints:
      - l_leg1_hip_y_joint
      - l_leg2_hip_r_joint
      - l_leg3_hip_p_joint
      - l_leg4_knee_p_joint
      - l_leg5_ankle_p_joint
      - l_leg6_ankle_r_joint
      - r_leg1_hip_y_joint
      - r_leg2_hip_r_joint
      - r_leg3_hip_p_joint
      - r_leg4_knee_p_joint
      - r_leg5_ankle_p_joint
      - r_leg6_ankle_r_joint
      - waist1_y_joint
      - waist2_p_joint
      - head1_y_joint
      - head2_p_joint
      - l_arm1_shoulder_p_joint
      - l_arm2_shoulder_r_joint
      - l_arm3_shoulder_y_joint
      - l_arm4_elbow_p_joint
      - l_arm5_wrist_y_joint
      - l_arm6_wrist_p_joint
      - l_arm7_wrist_r_joint
      - l_index_mcp_joint
      - l_middle_mcp_joint
      - l_pinky_mcp_joint
      - l_ring_mcp_joint
      - l_thumb_cmc_y_joint
      - l_thumb_cmc_p_joint
      - r_arm1_shoulder_p_joint
      - r_arm2_shoulder_r_joint
      - r_arm3_shoulder_y_joint
      - r_arm4_elbow_p_joint
      - r_arm5_wrist_y_joint
      - r_arm6_wrist_p_joint
      - r_arm7_wrist_r_joint
      - r_index_mcp_joint
      - r_middle_mcp_joint
      - r_pinky_mcp_joint
      - r_ring_mcp_joint
      - r_thumb_cmc_y_joint
      - r_thumb_cmc_p_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity